//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfIBMService.ServiceReferenceIBM {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferenceIBM.IServiceIBM")]
    public interface IServiceIBM {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceIBM/GetRates", ReplyAction="http://tempuri.org/IServiceIBM/GetRatesResponse")]
        string GetRates();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceIBM/GetRates", ReplyAction="http://tempuri.org/IServiceIBM/GetRatesResponse")]
        System.Threading.Tasks.Task<string> GetRatesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceIBM/GetTransactions", ReplyAction="http://tempuri.org/IServiceIBM/GetTransactionsResponse")]
        string GetTransactions();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceIBM/GetTransactions", ReplyAction="http://tempuri.org/IServiceIBM/GetTransactionsResponse")]
        System.Threading.Tasks.Task<string> GetTransactionsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceIBM/GetTransactionsOf", ReplyAction="http://tempuri.org/IServiceIBM/GetTransactionsOfResponse")]
        string GetTransactionsOf(string sku);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceIBM/GetTransactionsOf", ReplyAction="http://tempuri.org/IServiceIBM/GetTransactionsOfResponse")]
        System.Threading.Tasks.Task<string> GetTransactionsOfAsync(string sku);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceIBMChannel : WcfIBMService.ServiceReferenceIBM.IServiceIBM, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceIBMClient : System.ServiceModel.ClientBase<WcfIBMService.ServiceReferenceIBM.IServiceIBM>, WcfIBMService.ServiceReferenceIBM.IServiceIBM {
        
        public ServiceIBMClient() {
        }
        
        public ServiceIBMClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceIBMClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceIBMClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceIBMClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetRates() {
            return base.Channel.GetRates();
        }
        
        public System.Threading.Tasks.Task<string> GetRatesAsync() {
            return base.Channel.GetRatesAsync();
        }
        
        public string GetTransactions() {
            return base.Channel.GetTransactions();
        }
        
        public System.Threading.Tasks.Task<string> GetTransactionsAsync() {
            return base.Channel.GetTransactionsAsync();
        }
        
        public string GetTransactionsOf(string sku) {
            return base.Channel.GetTransactionsOf(sku);
        }
        
        public System.Threading.Tasks.Task<string> GetTransactionsOfAsync(string sku) {
            return base.Channel.GetTransactionsOfAsync(sku);
        }
    }
}
